# Generated by Django 5.0.2 on 2024-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cquizresult_equizresult_mquizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('choice_field', models.IntegerField(choices=[('Blind', 'Blind'), ('Deaf', 'Deaf')])),
            ],
        ),
    ]
